-- 게시판 테이블
CREATE TABLE BOARD_TBL (
	BOARD_ID NUMBER(10,0) PRIMARY KEY,
	BOARD_WRITER VARCHAR2(20) NOT NULL,
	-- 게시글 제목 필드 추가
	BOARD_TITLE VARCHAR2(100) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_DATE DATE DEFAULT SYSDATE
);

-- 게시판 삽입 이미지 테이블
CREATE TABLE BOARD_IMG_TBL (
	BOARD_IMG_ID NUMBER(10,0) PRIMARY KEY,
	BOARD_ID NUMBER(10,0) NOT NULL,
	BOARD_IMG VARCHAR2(200) NOT NULL
);

-- 게시판 테이블 시퀀스
CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1 
NOCACHE
NOCYCLE
MINVALUE 1 
MAXVALUE 9999999999;

-- 게시판 삽입 이미지 테이블 시퀀스
CREATE SEQUENCE BOARD_IMG_SEQ
START WITH 1
INCREMENT BY 1 
NOCACHE
NOCYCLE
MINVALUE 1 
MAXVALUE 9999999999;